services:
  web:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    environment:
      - ACTION=${ACTION:-}
      - MODE=${MODE:-}
      - PLATFORM=${PLATFORM:-android}
      - BUILD_FINGERPRINT=${BUILD_FINGERPRINT:-}
      - ANDROID_BASE_VERSION_CODE=${ANDROID_BASE_VERSION_CODE:-}
      - ANDROID_WEAR_VERSION_CODE=${ANDROID_WEAR_VERSION_CODE:-}
      - RELEASE_KEYSTORE=${RELEASE_KEYSTORE:-}
      - RELEASE_KEYSTORE_PASSPHRASE=${RELEASE_KEYSTORE_PASSPHRASE:-}
      - GRADLE_PROPERTIES=${GRADLE_PROPERTIES:-}
      - EXPO_HOST=${EXPO_HOST:-lan}
      - REACT_NATIVE_PACKAGER_HOSTNAME=${REACT_NATIVE_PACKAGER_HOSTNAME:-}
    working_dir: /app
    ports:
      - 8081:8081
