const {
  WarningAggregator,
  withMainActivity,
} = require('expo/config-plugins');

// Forwards Wear OS rotary input (crown / rotating bezel) to JS as
// DeviceEventEmitter('belgranoRotary', { delta }), consumed by components/watch/useRotaryScroll.js.
// `delta` is in physical pixels (already scaled by the system vertical scroll factor),
// positive = scroll down. Phones never produce SOURCE_ROTARY_ENCODER events, so the override
// falls through to the default dispatch there.

const PLUGIN = 'withBelgranoRotary';
const EVENT_NAME = 'belgranoRotary';
const BEGIN_MARKER = '  // @belgrano-rotary-begin (generated by plugins/withBelgranoRotary.js)';
const END_MARKER = '  // @belgrano-rotary-end';

const IMPORTS = [
  'android.view.InputDevice',
  'android.view.MotionEvent',
  'android.view.ViewConfiguration',
  'androidx.core.view.ViewConfigurationCompat',
  'com.facebook.react.ReactApplication',
  'com.facebook.react.bridge.Arguments',
  'com.facebook.react.bridge.ReactContext',
  'com.facebook.react.modules.core.DeviceEventManagerModule',
];

const METHODS = `${BEGIN_MARKER}
  override fun dispatchGenericMotionEvent(event: MotionEvent): Boolean {
    if (event.action == MotionEvent.ACTION_SCROLL &&
        event.isFromSource(InputDevice.SOURCE_ROTARY_ENCODER) &&
        belgranoEmitRotary(event)) {
      return true
    }

    return super.dispatchGenericMotionEvent(event)
  }

  private fun belgranoEmitRotary(event: MotionEvent): Boolean {
    val reactContext = belgranoCurrentReactContext() ?: return false

    return try {
      val factor = ViewConfigurationCompat.getScaledVerticalScrollFactor(
          ViewConfiguration.get(this), this)
      val delta = -event.getAxisValue(MotionEvent.AXIS_SCROLL) * factor

      if (delta == 0f) {
        return false
      }

      val params = Arguments.createMap()
      params.putDouble("delta", delta.toDouble())

      reactContext
          .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter::class.java)
          .emit("${EVENT_NAME}", params)
      true
    } catch (error: Throwable) {
      false
    }
  }

  @Suppress("DEPRECATION")
  private fun belgranoCurrentReactContext(): ReactContext? {
    // Old architecture: the ReactInstanceManager owned by ReactNativeHost.
    try {
      val host = (application as? ReactApplication)?.reactNativeHost
      if (host != null && host.hasInstance()) {
        val context = host.reactInstanceManager.currentReactContext
        if (context != null && context.hasActiveReactInstance()) {
          return context
        }
      }
    } catch (error: Throwable) {
      // Fall through to the bridgeless host below.
    }

    // New architecture / bridgeless: ReactHost.
    try {
      val context = (application as? ReactApplication)?.reactHost?.currentReactContext
      if (context != null && context.hasActiveReactInstance()) {
        return context
      }
    } catch (error: Throwable) {
      // No React context yet (e.g. splash screen); let the platform handle the event.
    }

    return null
  }
${END_MARKER}
`;

const addImports = contents => {
  const missing = IMPORTS.filter(name => !new RegExp(`^import ${name.replace(/\./g, '\\.')}$`, 'm').test(contents));

  if (missing.length === 0) {
    return contents;
  }

  const block = missing.map(name => `import ${name}`).join('\n');
  const importLines = [ ...contents.matchAll(/^import .*$/gm) ];

  if (importLines.length > 0) {
    const last = importLines[importLines.length - 1];
    const index = last.index + last[0].length;

    return `${contents.slice(0, index)}\n${block}${contents.slice(index)}`;
  }

  return contents.replace(/^(package .*\n)/m, `$1\n${block}\n`);
};

const removeGeneratedBlock = contents => {
  const begin = contents.indexOf(BEGIN_MARKER);
  const end = contents.indexOf(END_MARKER);

  if (begin === -1 || end === -1 || end < begin) {
    return contents;
  }

  return contents.slice(0, begin) + contents.slice(end + END_MARKER.length).replace(/^\n/, '');
};

const insertMethods = contents => {
  // Insert right before the closing brace of `class MainActivity`, i.e. the last `}` in the file.
  const closing = contents.lastIndexOf('}');

  if (closing === -1) {
    return null;
  }

  const before = contents.slice(0, closing).replace(/\s*$/, '\n');

  return `${before}\n${METHODS}${contents.slice(closing)}`;
};

const withRotaryMainActivity = config => withMainActivity(config, config => {
  if (config.modResults.language !== 'kt') {
    WarningAggregator.addWarningAndroid(PLUGIN, 'MainActivity is not Kotlin; rotary input was not forwarded to JS.');
    return config;
  }

  // Idempotent: drop a previously generated block, then write the current one.
  let contents = removeGeneratedBlock(config.modResults.contents);

  if (/override\s+fun\s+dispatchGenericMotionEvent\s*\(/.test(contents)) {
    WarningAggregator.addWarningAndroid(PLUGIN, 'MainActivity already overrides dispatchGenericMotionEvent; rotary input was not forwarded to JS.');
    config.modResults.contents = contents;
    return config;
  }

  const withMethods = insertMethods(contents);

  if (!withMethods) {
    WarningAggregator.addWarningAndroid(PLUGIN, 'Could not find the end of class MainActivity; rotary input was not forwarded to JS.');
    return config;
  }

  config.modResults.contents = addImports(withMethods);
  return config;
});

module.exports = function withBelgranoRotary(config) {
  return withRotaryMainActivity(config);
};

// Exposed for tests / inspection: applies the MainActivity transform to a Kotlin source string.
module.exports._apply = contents => {
  const withMethods = insertMethods(removeGeneratedBlock(contents));

  return withMethods ? addImports(withMethods) : contents;
};
