package __PACKAGE__

import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.TimeZone

// Generated by plugins/withBelgranoWear.js (BELGRANO_WEAR=1 builds only). Do not edit by hand.
// Reader for the trip snapshot written by BelgranoLiveTrip (see plugins/README-native.md).

internal data class WearDeparture(val departure: Long, val arrival: Long?, val source: String)

internal data class WearTracking(val active: Boolean, val nextStation: String?, val arrivalAt: Long?)

internal data class WearSnapshot(
    val origin: String,
    val destination: String,
    val departures: List<WearDeparture>,
    val fetchedAt: Long?,
    val tracking: WearTracking,
) {
    val route: String
        get() = "${BelgranoWearSnapshot.shortStation(origin)} → ${BelgranoWearSnapshot.shortStation(destination)}"

    // Trains still to leave at [now]; a train disappears the moment it departs.
    fun upcoming(now: Long): List<WearDeparture> =
        departures.filter { it.departure > now }.sortedBy { it.departure }
}

internal object BelgranoWearSnapshot {
    const val PREFS_NAME = "belgrano_trip_snapshot"
    const val PREFS_KEY = "json"
    const val ACTION_SUFFIX = ".TRIP_SNAPSHOT_UPDATED"

    private val ZONE: TimeZone = TimeZone.getTimeZone("America/Argentina/Buenos_Aires")

    fun read(context: Context): WearSnapshot? =
        parse(context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE).getString(PREFS_KEY, null))

    fun parse(json: String?): WearSnapshot? {
        if (json.isNullOrBlank()) {
            return null
        }

        return try {
            val root = JSONObject(json)
            val origin = root.optJSONObject("origin")?.optString("title").orEmpty()
            val destination = root.optJSONObject("destination")?.optString("title").orEmpty()

            if (origin.isEmpty() || destination.isEmpty()) {
                return null
            }

            val departures = mutableListOf<WearDeparture>()
            val rows = root.optJSONArray("departures")
            if (rows != null) {
                for (index in 0 until rows.length()) {
                    val row = rows.optJSONObject(index) ?: continue
                    val departure = row.optLong("departure", 0L)
                    if (departure <= 0L) {
                        continue
                    }
                    val arrival = if (row.isNull("arrival")) null else row.optLong("arrival", 0L).takeIf { it > 0L }
                    departures.add(WearDeparture(departure, arrival, row.optString("source", "scheduled")))
                }
            }

            val trackingJson = root.optJSONObject("tracking")
            val nextStation = when (val value = trackingJson?.opt("nextStation")) {
                is JSONObject -> value.optString("title").takeIf { it.isNotEmpty() }
                is String -> value.takeIf { it.isNotEmpty() }
                else -> null
            }
            val tracking = WearTracking(
                active = trackingJson?.optBoolean("active", false) ?: false,
                nextStation = nextStation,
                arrivalAt = trackingJson?.takeUnless { it.isNull("arrivalAt") }?.optLong("arrivalAt", 0L)?.takeIf { it > 0L },
            )

            WearSnapshot(
                origin = origin,
                destination = destination,
                departures = departures.sortedBy { it.departure },
                fetchedAt = root.optLong("fetchedAt", 0L).takeIf { it > 0L },
                tracking = tracking,
            )
        } catch (error: Exception) {
            null
        }
    }

    fun formatTime(millis: Long): String =
        SimpleDateFormat("HH:mm", Locale.US).apply { timeZone = ZONE }.format(Date(millis))

    // Whole minutes left; a train leaving in 6:40 reads "6 min" until it is 5:59 away.
    fun minutesUntil(target: Long, now: Long): Int =
        ((target - now) / 60_000L).toInt().coerceAtLeast(0)

    // "Boulogne Sur Mer" → "Boulogne" keeps the route on one line of a 192 dp watch.
    fun shortStation(title: String): String {
        val trimmed = title.trim()
        return if (trimmed.length <= 12) trimmed else trimmed.substringBefore(' ').ifEmpty { trimmed }
    }

    fun sourceLabel(context: Context, source: String): String = context.getString(
        when (source) {
            "live" -> R.string.wear_native_source_live
            "offline" -> R.string.wear_native_source_offline
            else -> R.string.wear_native_source_scheduled
        }
    )

    // "En vivo · hace 3 min" (or "Programado · recién").
    fun freshnessLabel(context: Context, source: String, fetchedAt: Long?, now: Long): String {
        val label = sourceLabel(context, source)
        if (fetchedAt == null) {
            return label
        }
        val minutes = minutesUntil(now, fetchedAt)
        return when {
            minutes < 1 -> context.getString(R.string.wear_native_updated_now, label)
            minutes < 120 -> context.getString(R.string.wear_native_updated_ago, label, minutes)
            else -> label
        }
    }

    fun launchPendingIntent(context: Context, requestCode: Int = 0): PendingIntent? {
        val intent = context.packageManager.getLaunchIntentForPackage(context.packageName)
            ?: Intent().setClassName(context, "${context.packageName}.MainActivity")
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP)

        return PendingIntent.getActivity(
            context,
            requestCode,
            intent,
            PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE,
        )
    }

    // Used by tile/complication previews in the watch face and tile editors.
    fun sample(now: Long): WearSnapshot = WearSnapshot(
        origin = "Boulogne Sur Mer",
        destination = "Retiro",
        departures = listOf(
            WearDeparture(now + 6 * 60_000L, now + 33 * 60_000L, "live"),
            WearDeparture(now + 21 * 60_000L, now + 48 * 60_000L, "scheduled"),
            WearDeparture(now + 36 * 60_000L, now + 63 * 60_000L, "scheduled"),
        ),
        fetchedAt = now,
        tracking = WearTracking(active = false, nextStation = null, arrivalAt = null),
    )
}
