package __PACKAGE__

import android.content.Context
import androidx.wear.watchface.complications.data.ComplicationData
import androidx.wear.watchface.complications.data.ComplicationText
import androidx.wear.watchface.complications.data.ComplicationType
import androidx.wear.watchface.complications.data.CountDownTimeReference
import androidx.wear.watchface.complications.data.LongTextComplicationData
import androidx.wear.watchface.complications.data.NoDataComplicationData
import androidx.wear.watchface.complications.data.PlainComplicationText
import androidx.wear.watchface.complications.data.RangedValueComplicationData
import androidx.wear.watchface.complications.data.ShortTextComplicationData
import androidx.wear.watchface.complications.data.TimeDifferenceComplicationText
import androidx.wear.watchface.complications.data.TimeDifferenceStyle
import androidx.wear.watchface.complications.datasource.ComplicationDataSourceService
import androidx.wear.watchface.complications.datasource.ComplicationDataSourceService.ComplicationRequestListener
import androidx.wear.watchface.complications.datasource.ComplicationRequest
import java.time.Instant
import java.util.concurrent.TimeUnit

// Generated by plugins/withBelgranoWear.js (BELGRANO_WEAR=1 builds only). Do not edit by hand.
//
// Next-train complication:
//   SHORT_TEXT   → "6 min" (title "07:40"); the countdown is a TimeDifferenceComplicationText,
//                  so the watch face keeps it current every minute without calling us again.
//   LONG_TEXT    → "Retiro 07:40"
//   RANGED_VALUE → minutes to departure (0–60) with the same countdown text.
// Refreshed by the snapshot broadcast and every UPDATE_PERIOD_SECONDS (manifest, 300 s).
class BelgranoNextTrainComplication : ComplicationDataSourceService() {

    override fun onComplicationRequest(
        request: ComplicationRequest,
        listener: ComplicationRequestListener,
    ) {
        val now = System.currentTimeMillis()
        listener.onComplicationData(build(this, request.complicationType, BelgranoWearSnapshot.read(this), now))
    }

    override fun getPreviewData(type: ComplicationType): ComplicationData? {
        val now = System.currentTimeMillis()
        return build(this, type, BelgranoWearSnapshot.sample(now), now)
    }

    companion object {
        private const val RANGE_MAX_MINUTES = 60f

        private fun plain(value: String): ComplicationText = PlainComplicationText.Builder(value).build()

        internal fun build(context: Context, type: ComplicationType, snapshot: WearSnapshot?, now: Long): ComplicationData {
            val tap = BelgranoWearSnapshot.launchPendingIntent(context, 1)
            val next = snapshot?.upcoming(now)?.firstOrNull()

            if (snapshot == null || next == null) {
                val description = plain(context.getString(R.string.wear_native_empty))
                return when (type) {
                    ComplicationType.SHORT_TEXT -> ShortTextComplicationData.Builder(plain("--"), description)
                        .setTapAction(tap)
                        .build()
                    ComplicationType.LONG_TEXT -> LongTextComplicationData.Builder(
                        plain(context.getString(if (snapshot == null) R.string.wear_native_empty_short else R.string.wear_native_no_trains)),
                        description,
                    )
                        .setTapAction(tap)
                        .build()
                    else -> NoDataComplicationData()
                }
            }

            val time = BelgranoWearSnapshot.formatTime(next.departure)
            val destination = BelgranoWearSnapshot.shortStation(snapshot.destination)
            val description = plain(context.getString(R.string.wear_native_complication_description, destination, time))
            val countdown = TimeDifferenceComplicationText.Builder(
                TimeDifferenceStyle.SHORT_WORDS_SINGLE_UNIT,
                CountDownTimeReference(Instant.ofEpochMilli(next.departure)),
            )
                .setMinimumTimeUnit(TimeUnit.MINUTES)
                .setDisplayAsNow(true)
                .build()

            return when (type) {
                ComplicationType.SHORT_TEXT -> ShortTextComplicationData.Builder(countdown, description)
                    .setTitle(plain(time))
                    .setTapAction(tap)
                    .build()
                ComplicationType.LONG_TEXT -> LongTextComplicationData.Builder(plain("$destination $time"), description)
                    .setTitle(plain(snapshot.route))
                    .setTapAction(tap)
                    .build()
                ComplicationType.RANGED_VALUE -> {
                    val minutes = BelgranoWearSnapshot.minutesUntil(next.departure, now).toFloat()
                    RangedValueComplicationData.Builder(
                        minutes.coerceIn(0f, RANGE_MAX_MINUTES),
                        0f,
                        RANGE_MAX_MINUTES,
                        description,
                    )
                        .setText(countdown)
                        .setTitle(plain(time))
                        .setTapAction(tap)
                        .build()
                }
                else -> NoDataComplicationData()
            }
        }
    }
}
