package __PACKAGE__

import android.content.BroadcastReceiver
import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.util.Log
import androidx.wear.tiles.TileService
import androidx.wear.watchface.complications.datasource.ComplicationDataSourceUpdateRequester

// Generated by plugins/withBelgranoWear.js (BELGRANO_WEAR=1 builds only). Do not edit by hand.
//
// Receives "<applicationId>.TRIP_SNAPSHOT_UPDATED" (sent by BelgranoLiveTrip after each publish,
// with setPackage(packageName) so this manifest receiver gets it) and refreshes the tile, the
// complication and the Ongoing Activity fallback.
class BelgranoWearSnapshotReceiver : BroadcastReceiver() {

    override fun onReceive(context: Context, intent: Intent) {
        if (intent.action != context.packageName + BelgranoWearSnapshot.ACTION_SUFFIX) {
            return
        }

        refresh(context)
    }

    companion object {
        private const val TAG = "BelgranoWearSnapshot"

        fun refresh(context: Context) {
            try {
                TileService.getUpdater(context).requestUpdate(BelgranoNextTrainTile::class.java)
            } catch (error: Exception) {
                Log.w(TAG, "Tile update request failed", error)
            }

            try {
                ComplicationDataSourceUpdateRequester
                    .create(context, ComponentName(context, BelgranoNextTrainComplication::class.java))
                    .requestUpdateAll()
            } catch (error: Exception) {
                Log.w(TAG, "Complication update request failed", error)
            }

            BelgranoWearOngoing.sync(context, BelgranoWearSnapshot.read(context))
        }
    }
}
