package __PACKAGE__

import android.content.Context
import androidx.concurrent.futures.CallbackToFutureAdapter
import androidx.wear.protolayout.ActionBuilders
import androidx.wear.protolayout.ColorBuilders.argb
import androidx.wear.protolayout.DeviceParametersBuilders.DeviceParameters
import androidx.wear.protolayout.DimensionBuilders.dp
import androidx.wear.protolayout.LayoutElementBuilders
import androidx.wear.protolayout.ModifiersBuilders
import androidx.wear.protolayout.ResourceBuilders
import androidx.wear.protolayout.TimelineBuilders
import androidx.wear.protolayout.material.ChipColors
import androidx.wear.protolayout.material.CompactChip
import androidx.wear.protolayout.material.Text
import androidx.wear.protolayout.material.Typography
import androidx.wear.protolayout.material.layouts.PrimaryLayout
import androidx.wear.tiles.RequestBuilders
import androidx.wear.tiles.TileBuilders
import androidx.wear.tiles.TileService
import com.google.common.util.concurrent.ListenableFuture

// Generated by plugins/withBelgranoWear.js (BELGRANO_WEAR=1 builds only). Do not edit by hand.
//
// "Next train" tile: route, next departure, "in N min", the following two departures and a
// freshness label, plus a chip that opens the app. The tile ships a timeline with one entry per
// minute boundary (up to TIMELINE_HORIZON_MS ahead), so "in N min" stays right without waking the
// app; the snapshot broadcast (BelgranoWearSnapshotReceiver) requests a fresh tile on every publish.
class BelgranoNextTrainTile : TileService() {

    override fun onTileRequest(
        requestParams: RequestBuilders.TileRequest
    ): ListenableFuture<TileBuilders.Tile> = CallbackToFutureAdapter.getFuture { completer ->
        completer.set(buildTile(this, requestParams.deviceConfiguration, System.currentTimeMillis()))
        "BelgranoNextTrainTile.onTileRequest"
    }

    override fun onTileResourcesRequest(
        requestParams: RequestBuilders.ResourcesRequest
    ): ListenableFuture<ResourceBuilders.Resources> = CallbackToFutureAdapter.getFuture { completer ->
        completer.set(ResourceBuilders.Resources.Builder().setVersion(RESOURCES_VERSION).build())
        "BelgranoNextTrainTile.onTileResourcesRequest"
    }

    companion object {
        private const val RESOURCES_VERSION = "1"
        private const val CLICK_OPEN_APP = "open_app"
        private const val MINUTE_MS = 60_000L
        private const val TIMELINE_HORIZON_MS = 90 * MINUTE_MS
        private const val MAX_TIMELINE_ENTRIES = 60
        private const val EMPTY_FRESHNESS_MS = 15 * MINUTE_MS
        private const val MAX_FRESHNESS_MS = 30 * MINUTE_MS

        private const val COLOR_ON_SURFACE = 0xFFFFF7F4.toInt()
        private const val COLOR_MUTED = 0xFFD8C2BD.toInt()
        private const val COLOR_LIVE = 0xFF7BD88F.toInt()
        private const val COLOR_CHIP = 0xFFBE4936.toInt()
        private const val COLOR_ON_CHIP = 0xFFFFFFFF.toInt()

        internal fun buildTile(context: Context, device: DeviceParameters, now: Long): TileBuilders.Tile {
            val snapshot = BelgranoWearSnapshot.read(context)
            val timeline = TimelineBuilders.Timeline.Builder()
            var freshness = EMPTY_FRESHNESS_MS

            val bounds = if (snapshot == null) emptyList() else timelineBounds(snapshot, now)

            if (bounds.isEmpty()) {
                timeline.addTimelineEntry(entry(layout(context, device, snapshot, now), null, null))
            } else {
                var start: Long? = null
                var renderAt = now
                for (end in bounds) {
                    timeline.addTimelineEntry(entry(layout(context, device, snapshot, renderAt), start, end))
                    start = end
                    renderAt = end
                }
                // Open-ended tail entry, then ask the system for a new tile once the timeline runs out.
                timeline.addTimelineEntry(entry(layout(context, device, snapshot, renderAt), start, null))
                freshness = (bounds.last() - now).coerceIn(MINUTE_MS, MAX_FRESHNESS_MS)
            }

            return TileBuilders.Tile.Builder()
                .setResourcesVersion(RESOURCES_VERSION)
                .setTileTimeline(timeline.build())
                .setFreshnessIntervalMillis(freshness)
                .build()
        }

        // Instants where the rendered text changes: every minute boundary before each upcoming
        // departure ("in 6 min" → "in 5 min") and the departure itself (switch to the next train).
        private fun timelineBounds(snapshot: WearSnapshot, now: Long): List<Long> {
            val limit = now + TIMELINE_HORIZON_MS
            val bounds = sortedSetOf<Long>()
            var previous = now

            for (departure in snapshot.upcoming(now).take(4)) {
                var instant = departure
                if (instant > limit) {
                    instant -= ((instant - limit + MINUTE_MS - 1) / MINUTE_MS) * MINUTE_MS
                }
                while (instant > previous) {
                    bounds.add(instant)
                    instant -= MINUTE_MS
                }
                previous = departure
                if (departure >= limit) {
                    break
                }
            }

            return bounds.take(MAX_TIMELINE_ENTRIES - 1)
        }

        private fun entry(
            root: LayoutElementBuilders.LayoutElement,
            start: Long?,
            end: Long?,
        ): TimelineBuilders.TimelineEntry {
            val builder = TimelineBuilders.TimelineEntry.Builder()
                .setLayout(LayoutElementBuilders.Layout.Builder().setRoot(root).build())

            if (start != null || end != null) {
                val validity = TimelineBuilders.TimeInterval.Builder()
                if (start != null) {
                    validity.setStartMillis(start)
                }
                if (end != null) {
                    validity.setEndMillis(end)
                }
                builder.setValidity(validity.build())
            }

            return builder.build()
        }

        private fun layout(
            context: Context,
            device: DeviceParameters,
            snapshot: WearSnapshot?,
            at: Long,
        ): LayoutElementBuilders.LayoutElement {
            val chip = CompactChip.Builder(
                context,
                context.getString(R.string.wear_native_open),
                openAppClickable(context),
                device,
            )
                .setChipColors(ChipColors(COLOR_CHIP, COLOR_ON_CHIP))
                .build()

            if (snapshot == null) {
                return PrimaryLayout.Builder(device)
                    .setContent(text(context, context.getString(R.string.wear_native_empty), Typography.TYPOGRAPHY_BODY1, COLOR_ON_SURFACE, 3))
                    .setPrimaryChipContent(chip)
                    .build()
            }

            val route = text(context, snapshot.route, Typography.TYPOGRAPHY_CAPTION1, COLOR_ON_SURFACE, 1)
            val upcoming = snapshot.upcoming(at)
            val next = upcoming.firstOrNull()

            if (next == null) {
                return PrimaryLayout.Builder(device)
                    .setPrimaryLabelTextContent(route)
                    .setContent(text(context, context.getString(R.string.wear_native_no_trains), Typography.TYPOGRAPHY_BODY1, COLOR_ON_SURFACE, 2))
                    .setPrimaryChipContent(chip)
                    .build()
            }

            val minutes = BelgranoWearSnapshot.minutesUntil(next.departure, at)
            val countdown = if (minutes < 1) {
                context.getString(R.string.wear_native_now)
            } else {
                context.getString(R.string.wear_native_in_minutes, minutes)
            }

            val content = LayoutElementBuilders.Column.Builder()
                .setHorizontalAlignment(LayoutElementBuilders.HORIZONTAL_ALIGN_CENTER)
                .addContent(text(context, BelgranoWearSnapshot.formatTime(next.departure), Typography.TYPOGRAPHY_DISPLAY2, COLOR_ON_SURFACE, 1))
                .addContent(text(context, countdown, Typography.TYPOGRAPHY_TITLE3, COLOR_ON_SURFACE, 1))

            val later = upcoming.drop(1).take(2)
            if (later.isNotEmpty()) {
                content
                    .addContent(LayoutElementBuilders.Spacer.Builder().setHeight(dp(2f)).build())
                    .addContent(
                        text(
                            context,
                            context.getString(R.string.wear_native_then, later.joinToString(" · ") { BelgranoWearSnapshot.formatTime(it.departure) }),
                            Typography.TYPOGRAPHY_CAPTION2,
                            COLOR_MUTED,
                            1,
                        )
                    )
            }

            val freshness = BelgranoWearSnapshot.freshnessLabel(context, next.source, snapshot.fetchedAt, at)

            return PrimaryLayout.Builder(device)
                .setPrimaryLabelTextContent(route)
                .setContent(content.build())
                .setSecondaryLabelTextContent(
                    text(context, freshness, Typography.TYPOGRAPHY_CAPTION2, if (next.source == "live") COLOR_LIVE else COLOR_MUTED, 1)
                )
                .setPrimaryChipContent(chip)
                .build()
        }

        private fun text(context: Context, value: String, typography: Int, color: Int, maxLines: Int): Text =
            Text.Builder(context, value)
                .setTypography(typography)
                .setColor(argb(color))
                .setMaxLines(maxLines)
                .setOverflow(LayoutElementBuilders.TEXT_OVERFLOW_ELLIPSIZE_END)
                .build()

        private fun openAppClickable(context: Context): ModifiersBuilders.Clickable =
            ModifiersBuilders.Clickable.Builder()
                .setId(CLICK_OPEN_APP)
                .setOnClick(
                    ActionBuilders.LaunchAction.Builder()
                        .setAndroidActivity(
                            ActionBuilders.AndroidActivity.Builder()
                                .setPackageName(context.packageName)
                                .setClassName("${context.packageName}.MainActivity")
                                .build()
                        )
                        .build()
                )
                .build()
    }
}
