package __PACKAGE__

import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.Context
import android.os.Build
import android.util.Log
import androidx.core.app.NotificationCompat
import androidx.core.app.NotificationManagerCompat
import androidx.wear.ongoing.OngoingActivity
import androidx.wear.ongoing.Status

// Generated by plugins/withBelgranoWear.js (BELGRANO_WEAR=1 builds only). Do not edit by hand.
//
// Ties the live-trip notification ("Seguir viaje") to a Wear OS Ongoing Activity, so the watch
// face and the recents list show the trip while tracking is active.
//
// Two integration paths (see docs/ui/notes/K.md):
//  1. Recommended: BelgranoLiveTrip calls apply(...) reflectively on its NotificationCompat.Builder
//     right before notify(); the class only exists in watch builds, so the phone build skips it:
//       Class.forName("$packageName.BelgranoWearOngoing")
//           .getMethod("apply", Context::class.java, Int::class.javaPrimitiveType,
//                      NotificationCompat.Builder::class.java, String::class.java)
//           .invoke(null, context, notificationId, builder, snapshotJson)
//  2. Fallback: BelgranoWearSnapshotReceiver calls sync(...) on every snapshot broadcast. It
//     upgrades an already-posted notification on CHANNEL_ID in place, or posts its own one
//     (tag WEAR_TAG, id LIVE_TRIP_NOTIFICATION_ID) when none exists.
object BelgranoWearOngoing {
    private const val TAG = "BelgranoWearOngoing"

    const val CHANNEL_ID = "belgrano-live-trip"
    const val LIVE_TRIP_NOTIFICATION_ID = 4210
    const val WEAR_TAG = "belgrano-wear-ongoing"
    private const val EXTRA_APPLIED = "belgrano.wearOngoingApplied"

    // Attaches the Ongoing Activity to [builder] when the snapshot says tracking is active.
    // Returns true when it did. Never throws: a failure only means no Ongoing Activity.
    @JvmStatic
    fun apply(context: Context, notificationId: Int, builder: NotificationCompat.Builder, snapshotJson: String?): Boolean {
        val snapshot = BelgranoWearSnapshot.parse(snapshotJson) ?: BelgranoWearSnapshot.read(context)
        return apply(context, notificationId, builder, snapshot)
    }

    @JvmStatic
    fun apply(context: Context, builder: NotificationCompat.Builder, snapshotJson: String?): Boolean =
        apply(context, LIVE_TRIP_NOTIFICATION_ID, builder, snapshotJson)

    internal fun apply(context: Context, notificationId: Int, builder: NotificationCompat.Builder, snapshot: WearSnapshot?): Boolean {
        if (snapshot == null || !snapshot.tracking.active) {
            return false
        }

        return try {
            builder.setOngoing(true)
            builder.setCategory(NotificationCompat.CATEGORY_NAVIGATION)
            builder.addExtras(android.os.Bundle().apply { putBoolean(EXTRA_APPLIED, true) })

            val launch = BelgranoWearSnapshot.launchPendingIntent(context, 2)
            val activity = OngoingActivity.Builder(context, notificationId, builder)
                .setStaticIcon(R.drawable.belgrano_wear_ongoing_icon)
                .setCategory(NotificationCompat.CATEGORY_NAVIGATION)
                .setStatus(status(context, snapshot))

            if (launch != null) {
                activity.setTouchIntent(launch)
            }

            activity.build().apply(context)
            true
        } catch (error: Exception) {
            Log.w(TAG, "Could not attach the Ongoing Activity", error)
            false
        }
    }

    // "Próxima: Villa Adelina · Llegás 02:51" (parts are skipped when unknown).
    private fun status(context: Context, snapshot: WearSnapshot): Status {
        val parts = mutableListOf<Pair<String, String>>()
        snapshot.tracking.nextStation?.let {
            parts.add("next" to context.getString(R.string.wear_native_next_station, it))
        }
        val arrival = snapshot.tracking.arrivalAt
            ?: snapshot.upcoming(System.currentTimeMillis()).firstOrNull()?.arrival
        arrival?.let {
            parts.add("eta" to context.getString(R.string.wear_native_arrive_at, BelgranoWearSnapshot.formatTime(it)))
        }
        if (parts.isEmpty()) {
            parts.add("route" to snapshot.route)
        }

        val builder = Status.Builder()
            .addTemplate(parts.joinToString(" · ") { "#${it.first}#" })
        for ((name, value) in parts) {
            builder.addPart(name, Status.TextPart(value))
        }
        return builder.build()
    }

    // Fallback path, called from the snapshot broadcast.
    internal fun sync(context: Context, snapshot: WearSnapshot?) {
        val manager = context.getSystemService(Context.NOTIFICATION_SERVICE) as? NotificationManager ?: return
        val tracking = snapshot?.tracking?.active == true

        if (!tracking) {
            // Only ever cancel the notification this class posted itself.
            manager.cancel(WEAR_TAG, LIVE_TRIP_NOTIFICATION_ID)
            return
        }

        if (!NotificationManagerCompat.from(context).areNotificationsEnabled()) {
            return
        }

        try {
            val existing = manager.activeNotifications.firstOrNull {
                it.tag != WEAR_TAG && it.notification.channelIdCompat() == CHANNEL_ID
            }

            if (existing != null) {
                if (existing.notification.extras.getBoolean(EXTRA_APPLIED, false)) {
                    return
                }
                val builder = NotificationCompat.Builder(context, existing.notification)
                if (apply(context, existing.id, builder, snapshot)) {
                    manager.notify(existing.tag, existing.id, builder.build())
                }
                // The live-trip module owns its notification; drop our stand-in if any.
                manager.cancel(WEAR_TAG, LIVE_TRIP_NOTIFICATION_ID)
                return
            }

            ensureChannel(context, manager)
            val text = listOfNotNull(
                snapshot!!.tracking.nextStation?.let { context.getString(R.string.wear_native_next_station, it) },
                snapshot.tracking.arrivalAt?.let { context.getString(R.string.wear_native_arrive_at, BelgranoWearSnapshot.formatTime(it)) },
            ).joinToString(" · ")

            val builder = NotificationCompat.Builder(context, CHANNEL_ID)
                .setSmallIcon(R.drawable.belgrano_wear_ongoing_icon)
                .setContentTitle(context.getString(R.string.wear_native_tracking_title, snapshot.route))
                .setContentText(text.ifEmpty { null })
                .setContentIntent(BelgranoWearSnapshot.launchPendingIntent(context, 3))
                .setOnlyAlertOnce(true)
                .setSilent(true)
                .setOngoing(true)

            if (apply(context, LIVE_TRIP_NOTIFICATION_ID, builder, snapshot)) {
                manager.notify(WEAR_TAG, LIVE_TRIP_NOTIFICATION_ID, builder.build())
            }
        } catch (error: SecurityException) {
            Log.w(TAG, "Notification permission missing; skipping the Ongoing Activity", error)
        } catch (error: Exception) {
            Log.w(TAG, "Could not sync the Ongoing Activity", error)
        }
    }

    private fun android.app.Notification.channelIdCompat(): String? =
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) channelId else null

    private fun ensureChannel(context: Context, manager: NotificationManager) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O || manager.getNotificationChannel(CHANNEL_ID) != null) {
            return
        }
        manager.createNotificationChannel(
            NotificationChannel(
                CHANNEL_ID,
                context.getString(R.string.wear_native_channel_name),
                NotificationManager.IMPORTANCE_LOW,
            )
        )
    }
}
