import * as Localization  from 'expo-localization';
import { I18n }           from 'i18n-js';

const Lang    = new I18n();
const locales = Localization.getLocales();

Lang.defaultLocale = 'en';
Lang.locale        = Lang.defaultLocale;

if (
    locales.length > 0
    &&
    typeof(locales[0]) != 'undefined'
) {
    Lang.locale = locales[0].languageCode;
} else {
    console.warn(`No locales detected, falling back to ${Lang.defaultLocale}.`);
}

Lang.enableFallback = true;
Lang.translations   = {
    en: {
        to: 'to',
        from: 'from',
        selectDestinationHint: 'Select a destination',
        goBackBtnLabel: 'Go back',
        noTripsFoundMessage: 'No trips found, please try again tomorrow.',
        hour: 'hour',
        hours: 'hours',
        minute: 'minute',
        minutes: 'minutes',
        second: 'second',
        seconds: 'seconds',
        remaining: 'remaining',
        and: 'and',
        nextTripMessage: 'Your next trip from',
        nextTripScheduleForMessage: 'is scheduled for',
        nextTripRemainingTimeMessage: '%s remaining',
        hurryUpMessage: 'The train will arrive in a few seconds!',
        fetchingTrainStationsMapMessage: 'Fetching train stations map',
        fetchingHolidaysListMessage: 'Fetching holidays list',
        fetchingAvailabilityOptionsMessage: 'Fetching availability options',
        detectingOriginStationMessage: 'Detecting origin station',
        locationAccessDeniedMessage: 'Location access is required, please enable it from the device settings.',
        locationUnknownErrorMessage: 'An unknown error prevented location access, please contact the developer.',
        originDetectionErrorMessage: 'Couldn\'t detect origin train station.',
        offlineModeHint: 'Offline',
        offlineModeInfoMessage: 'You\'re currently offline, schedule results will be loaded from memory until you\'re back online.',
        gotItBtnLabel: 'Got it',
        alternativeTripStartTimeMessage: 'Alternatively, take it at',
        fetchTrainStationsMapError: 'A connection error has occured while trying to fetch the train stations map, please try again later.',
        fetchHolidaysListError: 'A connection error has occured while trying to fetch the holidays list, please try again later.',
        fetchAvailabilityOptionsError: 'A connection error has occured while trying to fetch the availability options, please try again later.',
        getTargetSegmentError: 'Couldn\'t detect a compatible schedule segment for the current date, please try again later.',
        fetchNextTripTimeError: 'A connection error has occured while trying to fetch the next trip time, please try again later.',
        verifyCachedResourcesMessage: 'Checking for updates',
        fetchingNextTripTimeMessage: 'Fetching trip schedule',
        processingScheduleMessage: 'Processing scheduled trips',
        screenDestinationPickerName: 'Destinations',
        screenNextScheduleName: 'Next trip',
        screenOfflineModeInfoName: 'Offline mode',
        fromStationLabel: 'From',
        changeOriginBtnLabel: 'Change origin',
        chooseOriginHint: 'Choose your origin station',
        detectedOriginWarning: 'Detected station is %s km away',
        favoritesSectionTitle: 'Favorites',
        recentsSectionTitle: 'Recent trips',
        allDestinationsSectionTitle: 'All destinations',
        addFavoriteBtnLabel: 'Add favorite',
        removeFavoriteBtnLabel: 'Remove favorite',
        routeSavedMessage: 'Favorite route saved',
        routeRemovedMessage: 'Favorite route removed',
        themeModeSystem: 'System',
        themeModeLight: 'Light',
        themeModeDark: 'Dark',
        themeModeButtonLabel: 'Theme: %s',
        retryBtnLabel: 'Retry',
        selectThisOriginHint: 'Use %s as origin station',
        selectThisDestinationHint: 'See next trains to %s',
        sourceLiveEstimate: 'Live estimate',
        sourceScheduledTime: 'Scheduled time',
        sourceOfflineCached: 'Offline cached schedule',
        nextDeparturesTitle: 'Next departures',
        reverseRouteBtnLabel: 'Reverse route',
        remindMeBtnLabel: 'Remind me 5 min before',
        remindMeShortBtnLabel: 'Remind me',
        cancelReminderBtnLabel: 'Turn off reminder',
        reminderSetMessage: 'Reminder set',
        reminderSetShortMessage: 'Reminder set',
        reminderCanceledMessage: 'Reminder turned off',
        reminderUnavailableMessage: 'This train is too soon for a 5 minute reminder.',
        reminderUnavailableShortMessage: 'Too soon',
        reminderAlertTitle: 'Train reminder',
        reminderAlertBody: 'Your train from %s to %s leaves at %s.',
        manualOriginFallbackMessage: 'We could not detect your origin automatically. Please choose it manually.',
        materialYouEnabledLabel: 'Material You',
        notificationPermissionDeniedMessage: 'Notification permission is required to schedule reminders.',
        notificationPermissionDeniedShortMessage: 'Permission needed',
        notificationChannelName: 'Departure reminders'
    },
    es: {
        to: 'a',
        from: 'desde',
        selectDestinationHint: 'Seleccione un destino',
        goBackBtnLabel: 'Volver',
        noTripsFoundMessage: 'No se encontraron viajes, volvé a intentarlo mañana.',
        hour: 'hora',
        hours: 'horas',
        minute: 'minuto',
        minutes: 'minutos',
        second: 'segundo',
        seconds: 'segundos',
        remaining: 'resantes',
        and: 'y',
        nextTripMessage: 'Tu viaje de',
        nextTripScheduleForMessage: 'está programado para las',
        nextTripRemainingTimeMessage: 'dentro de %s',
        hurryUpMessage: '¡El tren llegará en unos pocos segundos!',
        fetchingTrainStationsMapMessage: 'Obteniendo mapa de estaciones',
        fetchingHolidaysListMessage: 'Obteniendo lista de feriados',
        fetchingAvailabilityOptionsMessage: 'Obteniendo opciones de disponibilidad',
        detectingOriginStationMessage: 'Detectando estación de origen',
        locationAccessDeniedMessage: 'El acceso a la ubicación es necesario, por favor, habilitálo desde los ajustes del dispositivo.',
        locationUnknownErrorMessage: 'Un error desconocido provocó que no se pudiera acceder a la ubicación, por favor, contactá al desarrollador.',
        originDetectionErrorMessage: 'No se pudo detectar la estación de origen.',
        offlineModeHint: 'Sin conexión',
        offlineModeInfoMessage: 'No tenés conexión a internet, verás resultados almacenados en la memoria hasta que vuelvas a estar en línea.',
        gotItBtnLabel: 'Entendido',
        alternativeTripStartTimeMessage: 'Alternativamente, tomálo a las',
        fetchTrainStationsMapError: 'Ocurrió un error de conexión al intentar obtener el mapa de estaciones de tren, por favor, volvé a intentarlo más tarde.',
        fetchHolidaysListError: 'Ocurrió un error de conexión al intentar obtener la lista de feriados, por favor, volvé a intentarlo más tarde.',
        fetchAvailabilityOptionsError: 'Ocurrió un error de conexión al intentar obtener la lista de opciones de disponibilidad, por favor, volvé a intentarlo más tarde.',
        getTargetSegmentError: 'No se pudo detectar un segmento de tarifa compatible con la fecha actual, por favor, volvé a intentarlo más tarde.',
        fetchNextTripTimeError: 'Ocurrió un error de conexión al intentar obtener la hora del próximo viaje, por favor, volvé a intentarlo más tarde.',
        verifyCachedResourcesMessage: 'Comprobando actualizaciones',
        fetchingNextTripTimeMessage: 'Obteniendo programa de horarios',
        processingScheduleMessage: 'Procesando viajes programados',
        screenDestinationPickerName: 'Destinos',
        screenNextScheduleName: 'Próximo viaje',
        screenOfflineModeInfoName: 'Modo sin conexión',
        fromStationLabel: 'Desde',
        changeOriginBtnLabel: 'Cambiar origen',
        chooseOriginHint: 'Elegí tu estación de origen',
        detectedOriginWarning: 'La estación detectada está a %s km',
        favoritesSectionTitle: 'Favoritos',
        recentsSectionTitle: 'Viajes recientes',
        allDestinationsSectionTitle: 'Todos los destinos',
        addFavoriteBtnLabel: 'Agregar favorito',
        removeFavoriteBtnLabel: 'Quitar favorito',
        routeSavedMessage: 'Ruta guardada como favorita',
        routeRemovedMessage: 'Ruta quitada de favoritos',
        themeModeSystem: 'Sistema',
        themeModeLight: 'Claro',
        themeModeDark: 'Oscuro',
        themeModeButtonLabel: 'Tema: %s',
        retryBtnLabel: 'Reintentar',
        selectThisOriginHint: 'Usar %s como estación de origen',
        selectThisDestinationHint: 'Ver próximos trenes a %s',
        sourceLiveEstimate: 'Estimación en vivo',
        sourceScheduledTime: 'Horario programado',
        sourceOfflineCached: 'Horario guardado sin conexión',
        nextDeparturesTitle: 'Próximas salidas',
        reverseRouteBtnLabel: 'Invertir ruta',
        remindMeBtnLabel: 'Avisarme 5 min antes',
        remindMeShortBtnLabel: 'Avisarme',
        cancelReminderBtnLabel: 'Desactivar recordatorio',
        reminderSetMessage: 'Recordatorio activado',
        reminderSetShortMessage: 'Activado',
        reminderCanceledMessage: 'Recordatorio desactivado',
        reminderUnavailableMessage: 'Este tren sale demasiado pronto para avisarte 5 minutos antes.',
        reminderUnavailableShortMessage: 'Sale muy pronto',
        reminderAlertTitle: 'Recordatorio de tren',
        reminderAlertBody: 'Tu tren desde %s hacia %s sale a las %s.',
        manualOriginFallbackMessage: 'No pudimos detectar tu origen automáticamente. Elegilo manualmente.',
        materialYouEnabledLabel: 'Material You',
        notificationPermissionDeniedMessage: 'Necesitamos permiso de notificaciones para programar recordatorios.',
        notificationPermissionDeniedShortMessage: 'Falta permiso',
        notificationChannelName: 'Recordatorios de salida'
    }
}

console.log('locale:', Lang.locale);

export default Lang;
